version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  graphdb:
    image: jcm300/mb_graphdb:1.0.0
    ports:
      - "7200:7200"
  server:
    image: jcm300/musike_api:1.0.0
    restart: on-failure
    links:
      - mongo
      - graphdb
    ports:
      - "3000:3000"
  interface:
    image: jcm300/musike_interface:1.0.1
    links:
      - server
    ports:
      - "8080:7777"
volumes:
  db-data:
