version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  graphdb:
    image: mb_graphdb
    build:
      context: ./graphdb-free-8.9.0
      dockerfile: Dockerfile
    ports:
      - "7200:7200"
  server:
    image: musike_api
    build:
      context: ./APIserver
      dockerfile: Dockerfile
    restart: on-failure
    links:
      - mongo
      - graphdb
    ports:
      - "3000:3000"
  interface:
    image: musike_interface
    build:
      context: ./interface
      dockerfile: Dockerfile
    links:
      - server
    ports:
      - "8080:7777"
volumes:
  db-data:
